name: realworld_test

task_name: test

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    wrist_img:
      shape: [480, 640, 3]
      type: rgb
    force:
      shape: [3]
      type: low_dimx
    state:
      shape: [13]
      type: low_dimx
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.realworld_dataset.RealWorldDataset
  zarr_path: data/real-world_easy_10Hz_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
